sudo: required

services:
  - docker

before_install:
- docker build -t joramk/fc28-base:latest .
- docker run --name fc28_base --tmpfs /run --tmpfs /tmp -v /sys/fs/cgroup:/sys/fs/cgroup:ro -d joramk/fc28-base:latest

script:
- while sleep 5; do docker top fc28_base ; docker logs fc28_base ; docker ps -a | grep ago ; if [ `docker ps -a | grep '(unhealthy)' | wc -l` != "0" ]; then exit 1; fi ; if [ `docker ps -a | grep '(healthy)' | wc -l` != "0" ]; then exit 0; fi ; if [ `docker ps -a | grep 'starting)' | wc -l` == "0" ]; then exit 1; fi ; done
